"""external

Revision ID: 2d477bf6f993
Revises: e035808322c1
Create Date: 2026-03-30 21:23:47.045569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d477bf6f993'
down_revision = 'e035808322c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('album', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('source_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('src',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=False)
        batch_op.alter_column('cover',
               existing_type=sa.VARCHAR(length=300),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_song_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_source_id'), ['source_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_song_source_id'))
        batch_op.drop_index(batch_op.f('ix_song_source'))
        batch_op.alter_column('cover',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=True)
        batch_op.alter_column('src',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=300),
               existing_nullable=False)
        batch_op.drop_column('source_id')
        batch_op.drop_column('source')
        batch_op.drop_column('duration')
        batch_op.drop_column('album')

    # ### end Alembic commands ###
