"""Add youtube_id and source to Song

Revision ID: b2b51e3357dc
Revises: 2d477bf6f993
Create Date: 2026-04-17 17:34:09.129355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b51e3357dc'
down_revision = '2d477bf6f993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('youtube_id', sa.String(length=50), nullable=True))
        batch_op.alter_column('src',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=False)
        batch_op.alter_column('cover',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               server_default="local",
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_song_source'))
        batch_op.drop_index(batch_op.f('ix_song_source_id'))
        batch_op.create_unique_constraint('uq_song_youtube_id', ['youtube_id'])
        batch_op.drop_column('album')
        batch_op.drop_column('duration')
        batch_op.drop_column('source_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('song', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_id', sa.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('album', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_constraint('uq_song_youtube_id', type_='unique')
        batch_op.create_index(batch_op.f('ix_song_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_song_source'), ['source'], unique=False)
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cover',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.alter_column('src',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
        batch_op.drop_column('youtube_id')

    pass

    # ### end Alembic commands ###
